

# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: $(buildPlatformPipeline)
  buildConfiguration: $(buildConfigurationPipeline)

steps:


- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

# ASP.NET
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) /p:Platform=$(buildPlatform) ' 
    
    

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    configuration: '$(buildConfiguration)'
    publishWebProjects: false
    projects: '**/*.csproj'